#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BSFrameworks_Example' do
  pod 'BSFrameworks', :path => '../'
  
 # pod 'TZImagePickerController'
  
  target 'BSFrameworks_Tests' do
    inherit! :search_paths

    
  end
end
