#use_frameworks!

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BSFrameworks_Example' do
  pod 'BSFrameworks', :path => '../'
  
  pod 'TZImagePickerController'
  pod 'MJRefresh'
  pod 'MLeaksFinder'
  pod 'SDWebImage','~> 5.0'
  target 'BSFrameworks_Tests' do
    inherit! :search_paths

    
  end
end
