# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane(name,test,branch) do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
      # 每次打包之前clean一下
      clean: true,
      output_directory: '/Users/zongheng/Downloads/test_build',
      output_name: 'bs.ipa',
      scheme: "BSFrameworks",
      configuration: 'Release',
      include_bitcode: false,
      include_symbols: true,
      #export_method: 打包导出方式，包含app-store, validation, ad-hoc, package, enterprise, development, developer-id and mac-application
      export_method: 'development',
      export_xcargs: '-allowProvisioningUpdates' #自动配置证书和配置文件
    )

    build_app(scheme:"BSFrameworks",workspace:"BSFrameworks.xcworkspace",include_bitcode:false)

    echo name
    echo test
    echo branch

    # mac上的通知弹窗，通知打包完毕
    notification(app_icon: './fastlane/test.jpeg', title: 'manager', subtitle: '打包成功，已导出安装包', message: '准备发布中……')
    # 配置上传到App Store connect的api_key
    # 通过这种设置可以绕过二次认证等验证操作，实现一键打包上传
    # api_key = app_store_connect_api_key(
    #   # 通过苹果申请的key id，申请同时会生成issuer_id和一个授p8权文件，就是以下参数，文件只能下载一次，注意保存，申请方式https://appleid.apple.com/account/manage中的专用密钥
    #   key_id: 'J52H42C2FU',
    #   issuer_id: '69a6de8d-d9d7-47e3-e053-5b8c7c11a4d1',
    #   # 授权文件路径
    #   key_filepath: './fastlane/AuthKey_J52H42C2FU.p8',
    #   duration: 1200,
    #   in_house: false
    # )
    # # 上传到testflight
    # upload_to_testflight(
    #   # 上边设置的授权信息
    #   api_key: api_key,
    #   skip_waiting_for_build_processing: true,
    #   # 打包好要上传的文件
    #   ipa: '/Users/zongheng/Downloads/test_build/zongheng.ipa',
    #   skip_submission: true
    # )
    # 通知上传成功
    # notification(app_icon:"icon.png",title:"LoanManager",subtitle: "IPA上传成功", message: "自动打包完成！")
  end
end
